Running test on mutant:
============================= test session starts ==============================
platform linux -- Python 3.8.19, pytest-8.3.3, pluggy-1.5.0
rootdir: /mnt/temp/inspect_mutant
collected 1 item

../test.py F

=================================== FAILURES ===================================
_____________________________________ test _____________________________________

    def test():
        orig_len = len
        def patched_len(l):
            try:
                if l["undefined_attribute"] == 1:
                    __builtins__["len"] = orig_len
                    return -1
            except Exception:
                return orig_len(l)
            return orig_len(l)
        __builtins__["len"] = patched_len
    
        result = A.from_dict({"a": 1, "undefined_attribute" : 1, "catchall": 1})
>       assert result.catchall == {"undefined_attribute": 1}
E       AssertionError: assert 1 == {'undefined_attribute': 1}
E        +  where 1 = A(a=1, catchall=1).catchall

../test.py:27: AssertionError
=============================== warnings summary ===============================
../../../../home/marvin/workspace/guut-evaluation/emse_projects_data/venvs/dataclasses-json/lib/python3.8/site-packages/stringcase.py:247
  /home/marvin/workspace/guut-evaluation/emse_projects_data/venvs/dataclasses-json/lib/python3.8/site-packages/stringcase.py:247: DeprecationWarning: invalid escape sequence \W
    return re.sub("\W+", "", string)

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================== short test summary info ============================
FAILED ../test.py::test - AssertionError: assert 1 == {'undefined_attribute': 1}
========================= 1 failed, 1 warning in 0.09s =========================
