Running test on mutant:
============================= test session starts ==============================
platform linux -- Python 3.8.19, pytest-8.3.3, pluggy-1.5.0
rootdir: /mnt/temp/inspect_mutant
collected 1 item

../test.py F

=================================== FAILURES ===================================
_____________________________________ test _____________________________________

    def test():
        output = StringIO()
        logger = logging.getLogger()
        logger.setLevel(logging.DEBUG)
        logger.addHandler(logging.StreamHandler(output))
    
        with TemporaryDirectory() as tempdir:
            (Path(tempdir) / "path").mkdir()
            (Path(tempdir) / "path" / "sub1.pyi").write_text("__all__ = []; import missing")
            (Path(tempdir) / "path" / "sub2.pyi").write_text("__all__ = []; import missing")
            (Path(tempdir) / "path" / "sub3.pyi").write_text("__all__ = []; import missing")
            (Path(tempdir) / "main.py").write_text(f"__path__ = ['{tempdir}/path'];")
            sys.path.append(tempdir)
    
            orig_len = len
            def patched_len(l):
                try:
                    if l[0] == 'main.sub1':
                        __builtins__["len"] = orig_len
                        return -1
                except Exception:
                    return orig_len(l)
                return orig_len(l)
    
            __builtins__["len"] = patched_len
    
            try:
                load_root("main", "main")
            except ModuleNotFoundError:
                pass
    
>           assert "Load stub" not in output.getvalue()
E           AssertionError: assert 'Load stub' not in 'Module path... main.sub1\n'
E             
E             'Load stub' is contained here:
E               Module path: ['/tmp/tmp5xgx68l0/path']
E               Load stub: main.sub3
E               Load stub: main.sub2
E               Load stub: main.sub1

../test.py:43: AssertionError
------------------------------ Captured log call -------------------------------
DEBUG    root:compiler.py:450 Module path: ['/tmp/tmp5xgx68l0/path']
DEBUG    root:compiler.py:419 Load stub: main.sub3
DEBUG    root:compiler.py:419 Load stub: main.sub2
DEBUG    root:compiler.py:419 Load stub: main.sub1
=========================== short test summary info ============================
FAILED ../test.py::test - AssertionError: assert 'Load stub' not in 'Module p...
============================== 1 failed in 0.03s ===============================
