Running test on mutant:
============================= test session starts ==============================
platform linux -- Python 3.8.19, pytest-8.3.3, pluggy-1.5.0
rootdir: /mnt/temp/inspect_mutant
collected 1 item

../../test.py F

=================================== FAILURES ===================================
_____________________________________ test _____________________________________

    def test():
        FlakesChecker.with_doctest = False
        FlakesChecker.include_in_doctest = ["filename.py"]
        checker = FlakesChecker(ast.parse("import sys"), (), "filename.py")
>       assert checker.withDoctest
E       assert False
E        +  where False = <flake8.plugins.pyflakes.FlakesChecker object at 0x71f73f589d00>.withDoctest

../../test.py:10: AssertionError
=========================== short test summary info ============================
FAILED ../../test.py::test - assert False
============================== 1 failed in 0.06s ===============================
