Running test on mutant:
============================= test session starts ==============================
platform linux -- Python 3.8.19, pytest-8.3.3, pluggy-1.5.0
rootdir: /mnt/temp/inspect_mutant
collected 1 item

../test.py F

=================================== FAILURES ===================================
_____________________________________ test _____________________________________

    def test():
        pa = PrettyAttribute("name", (AttrCategory.DESCRIPTOR,), dummy_function)
>       assert "2" not in pa.get_oneline_doc()
E       AssertionError: assert '2' not in 'class funct...th getter, 2'
E         
E         '2' is contained here:
E           class function with getter, 2
E         ?                             +

../test.py:11: AssertionError
=========================== short test summary info ============================
FAILED ../test.py::test - AssertionError: assert '2' not in 'class funct...th...
============================== 1 failed in 0.03s ===============================
