Running test on mutant:
============================= test session starts ==============================
platform linux -- Python 3.8.19, pytest-8.3.3, pluggy-1.5.0
rootdir: /tmp/inspect_mutant
collected 1 item

../test.py F

=================================== FAILURES ===================================
_____________________________________ test _____________________________________

    def test():
        try:
            roman_range(MockInt(1), 123, 1)
        except OverflowError:
            pass
    
>       assert i == 0
E       assert 1 == 0

../test.py:16: AssertionError
=========================== short test summary info ============================
FAILED ../test.py::test - assert 1 == 0
============================== 1 failed in 0.04s ===============================
