Running test on mutant:
============================= test session starts ==============================
platform linux -- Python 3.8.19, pytest-8.3.3, pluggy-1.5.0
rootdir: /mnt/temp/inspect_mutant
collected 1 item

../test.py F

=================================== FAILURES ===================================
_____________________________________ test _____________________________________

    def test():
        orig_isinstance = __builtins__["isinstance"]
    
        def mock_isinstance(obj, cls):
            if orig_isinstance(obj, cls):
                return True
            return orig_isinstance(obj, MockInt)
    
        __builtins__["isinstance"] = mock_isinstance
        try:
            roman_range(MockInt(1), 123, 1)
        except OverflowError:
            pass
    
>       assert i == 0
E       assert 1 == 0

../test.py:24: AssertionError
=========================== short test summary info ============================
FAILED ../test.py::test - assert 1 == 0
============================== 1 failed in 0.04s ===============================
